홍준표 java-lotto 과제 제출
nuyh99/java-lotto pull request #3
Opened 2023-06-29 10:37 UTC by howudong

열심히했씁니다.

2023-07-02 10:50 UTC, nuyh99 requested changes

2023-07-02 10:50 UTC, nuyh99 commented on docs/README.md
> +    - [ ] 총 수익률을 지닌다.
얘네도 체크 되면 좋겠네요!

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Application.java
> +        new Controller().startLottoGame();
<img width="566" alt="image" src="https://github.com/nuyh99/java-lotto/assets/93072571/5b4a05d6-95a0-445d-8ca2-795f6305143d"><br>

예외가 터졌지만 그대로 진행이 되는 모습이네요.
사용자는 알 수 없는 빨간 문자들을 본 뒤 다음으로 진행되는데 괜찮은 경험일까요?
`printStackTrace()`는 무슨 메서드일까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +    public static final int PRICE_OF_LOTTO = 1000;
public...!
상수와 인스턴스 변수 사이는 한 줄 띄워도 좋을 것 같네요

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +    private static List<List<Integer>> lotto;
만들어둔 VO를 써도 좋을 것 같습니다.
`List<Lotto>`의 형태가 더 명확하지 않을까요??

`lotto`라는 네이밍 보다는 `purchasedLottos` 등이 더 명확할 것 같아요.

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +            return;
return 문이 필요할까요?
그리고 현재 `IllegalArgumentException`이 발생해도 프로그램이 종료되지 않는 것 같습니다.

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +        BuyLottoView buyLottoView = new BuyLottoView();
로또를 구입할 때마다 매번 새로운 `BuyLottoView` 인스턴스가 생성될 것 같네요.

`Controller`의 필드에 아래와 같은 형태로 가져도 되지 않을까요?
```java
private final BuyLottoView buyLottoView;
```

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +            lotto = new Computer().buyLottoByPrice(buyLottoView.readPrice());
`Computer` 클래스는 여기서 매번 새로 생성된 뒤 `buyLottoByPrice`를 호출합니다.
저 메서드만 호출하는 용도로 인스턴스를 생성하는 것 외 다른 방법은 없을까요?
```java
lotto = Computer.buyLottoByPrice(buyLottoView.readPrice());
```
static을 이용할 수도 있겠네요

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +            if (rank == LottoRank.UNRANKED) continue;
```suggestion
if (LottoRank.UNRANKED.equals(rank)) {
     continue;
}
```
중괄호를 생략하는 컨벤션은 없습니다!

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +        double average = lottoResult.getAverageProfit(lotto.size() * PRICE_OF_LOTTO);
```suggestion
int totalPrice = lotto.size() * PRICE_OF_LOTTO;
double average = lottoResult.getAverageProfit(totalPrice);
```
개인적으로 이게 더 보기 쉬운 것 같아요

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +        System.out.println(lottoResultView.getViewAverageProfit(average));
출력을 하는 것까지 View의 역할이 아닐까요?
```suggestion
    lottoResultView.printAverageProfit(average);
```

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/Controller.java
> +                .getViewRankInfo(rank.getValue(), rank.getMoney(), amount, rank == LottoRank.SECOND));
마찬가지로 View의 역할을 컨트롤러가 하고 있는 것 같습니다.

System.out.println으로 콘솔에 출력하고 있지만 출력 대상이 달라지면 어떻게 될까요?
지금은 컨트롤러와 뷰 모두 수정해야 할 것 같습니다.
하지만 `lottoResultView`에게 메세지를 보낸다면 뷰의 코드만 수정해도 되지 않을까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +    public Lotto(String readSentence) {
`String`으로 받는 것은 도메인이 뷰를 아는 상태 아닐까요?
입력 포맷에 대한 검증이 도메인의 역할일까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +        if (!validateNumRange(testNumbers)) {
Num은 Number의 축약형인 것 같습니다.
축약해서 쓰지 않는 것이 컨벤션입니다!

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +        return size == LOTTO_NUMBER_SIZE;
`LOTTO_NUMBER_SIZE`를 LottoGenerator에서 가져올 이유가 있을까요?

1. 오히려 `Lotto` 클래스 내부에서 더 자주 쓰이는 것 같다
2. LottoGenerator와 의존이 생겼는데 어떤 장단점이 있을까?
3. 의존을 해야 한다면 LottoGenerator에게 메세지를 보내는 방법은 지금의 방법에 비해 어떤 장단점을 가질까?

위의 문제들에 대해서 어떻게 생각하시나요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +    }
```suggestion
private List<Integer> splitNumberGroup(String[] readNumbers) {
        try {
            return Arrays.stream(readNumbers)
                    .mapToInt(Integer::parseInt)
                    .boxed()
                    .collect(Collectors.toList());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("[ERROR] 입력은 숫자만 가능합니다");
        }
    }
```
위와 같이 바꿀 수 있을 것 같습니다.

1. `throws`는 어떤 상황에서 쓰는 것일까요?
2. 문자열을 정수 리스트로 변환하는 것은 `Lotto`의 역할일까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +    final List<Integer> getNumbers() {
여기에만 final을 붙인 이유가 뭔지 궁금합니다.

package private 활용👍

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/WinningLotto.java
> +public final class WinningLotto extends Lotto {
상속을 이용한 이유가 궁금합니다.
어떤 장단점이 있을까요??

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/lottonumber/WinningLotto.java
> +    private boolean isOverpopulation(String bonus) {
over population의 뜻이 뭘까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/views/BuyLottoView.java
> +public final class BuyLottoView {
클래스명이 동사로 시작해도 될까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/views/BuyLottoView.java
> +    public void getViewPurchasedLotto(List<List<Integer>> lotto) {
get보단 print가 맞는 것 같네요
```java
public void printPurchasedLottos(List<List<Integer>> lotto) {
```

2023-07-02 10:50 UTC, nuyh99 commented on src/test/java/domain/ComputerTest.java
> +    void buyLottoByInvalidPrice() {
실패하는 테스트가 존재하는 것 같네요.
왜 실패할까요?
실패하는 테스트가 존재해도 될까요?

2023-07-02 10:50 UTC, nuyh99 commented on src/main/java/lotto/domain/LottoResult.java
> +    }
이건 계산 로직 같은데 테스트가 필요하지 않을까요??

2023-07-02 10:50 UTC, nuyh99 commented on src/test/java/domain/WinningLottoTest.java
> +    @DisplayName("매칭 결과 Lott Rank SECOND 여야한다.")
DisplayName이 잘못된 것 같네요!

2023-07-02 10:50 UTC, nuyh99 commented on src/test/java/domain/WinningLottoTest.java
> +class WinningLottoTest {
꼼꼼한 테스트👍

2023-07-04 08:23 UTC, howudong commented on src/main/java/lotto/Application.java
> +        new Controller().startLottoGame();
- Controller 부분에 예외처리를 추가함으로써, 정상적으로 끝내게 만들었습니다.
- printStackTrace()는 예외 정보를 출력하는 것인데, 사용자 입장에서는 없는게 낫을것 같아서 없앴습니다.
- 빨간 문자가 뜨는 에러를 제거했습니다.

2023-07-04 08:25 UTC, howudong commented on src/main/java/lotto/Controller.java
> +    public static final int PRICE_OF_LOTTO = 1000;
수정했습니다!

2023-07-04 08:26 UTC, howudong commented on src/main/java/lotto/Controller.java
> +            return;
해당 부분의 try catch를 없애고 controller에 추가함으로써 해당 버그를 수정했습니다.

2023-07-04 08:38 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +        if (!validateNumRange(testNumbers)) {
validateNumRange -> validateNumberRange로 수정했습니다.

2023-07-04 08:39 UTC, howudong commented on src/main/java/lotto/Controller.java
> +            if (rank == LottoRank.UNRANKED) continue;
리팩토링 했습니다.

2023-07-04 08:43 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/WinningLotto.java
> +    private boolean isOverpopulation(String bonus) {
중복이란 의미로 사용했는데 검색을 잘못한 것 같습니다.

overPopulation -> isDuplicate로 함수명을 수정했습니다.

2023-07-04 08:44 UTC, howudong commented on src/main/java/lotto/views/BuyLottoView.java
> +public final class BuyLottoView {
BuyLottoView -> LottoBuyView로 클래스명을 수정했습니다.

2023-07-04 08:46 UTC, howudong commented on src/main/java/lotto/views/BuyLottoView.java
> +    public void getViewPurchasedLotto(List<List<Integer>> lotto) {
LottoBuyView에서 get으로 시작하는 함수명을 전부 print로 바꿨습니다.

2023-07-04 08:47 UTC, howudong commented on src/test/java/domain/ComputerTest.java
> +    void buyLottoByInvalidPrice() {
실패하는 테스트를 없앴습니다!

실패했던 이유는 해당 테스트는 예외를 발생시키는 것이 아닌,
발생한 예외를 처리하는 것이었기 때문입니다.

2023-07-04 09:02 UTC, howudong commented on src/main/java/lotto/Controller.java
> +        double average = lottoResult.getAverageProfit(lotto.size() * PRICE_OF_LOTTO);
위 형식으로 보기 쉽게 수정했습니다.

2023-07-04 09:07 UTC, howudong commented on src/main/java/lotto/Controller.java
> +        System.out.println(lottoResultView.getViewAverageProfit(average));
```suggestion
        lottoResultView.printViewAverageProfit(average);
    }
``` 



## LottoResultView.java
``` 
  public void printViewAverageProfit(double average) {
          System.out.printf("총 수익률은 %.1f%%입니다.\n", average * 100);
      }
```
view에서 출력하도록 클래스를 옮겼습니다

2023-07-04 09:09 UTC, howudong commented on src/main/java/lotto/Controller.java
> +                .getViewRankInfo(rank.getValue(), rank.getMoney(), amount, rank == LottoRank.SECOND));
```suggestion
       lottoResultView.printViewRankInfo(rank.getValue(), rank.getMoney(), amount, rank == LottoRank.SECOND);
```

## LottoResultView.java
```
public void printViewRankInfo(int matches, int money, int amount, boolean bonus) {
        if (bonus) {
            System.out.printf("%d개 일치, 보너스 볼 일치 (%,d원) - %d개\n", matches, money, amount);
            return;
        }
        System.out.printf("%d개 일치 (%,d원) - %d개\n", matches, money, amount);
    }
```

view에서 출력하도록 옮겼습니다.

2023-07-05 06:18 UTC, howudong commented on src/main/java/lotto/Controller.java
> +    private static List<List<Integer>> lotto;
List<Integer> 대신 Lotto를 사용하도록 변경했습니다.
그리고 lotto 네이밍을 좀 더 정확하게 했습니다.

2023-07-05 06:39 UTC, howudong commented on src/test/java/domain/WinningLottoTest.java
> +    @DisplayName("매칭 결과 Lott Rank SECOND 여야한다.")
잘못된 DisplayName 수정했습니다!

2023-07-05 12:00 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +    public Lotto(String readSentence) {
```
public final class InputReadView {

    public String readPrice() {
        System.out.println("구입금액을 입력해 주세요.");
        String readNumber = Console.readLine();

        validateNumber(readNumber);
        return readNumber;
    }

    public String readLottoNumbers() {
        System.out.println("로또 번호를 입력해주세요.");
        String readSentence = Console.readLine();

        validateLottoFormat(readSentence);

        return readSentence;
    }

    public String readBonusNumber() {
        System.out.println();
        System.out.println("보너스 번호를 입력해주세요.\n");

        String bonusNumber = Console.readLine();

        validateNumber(bonusNumber);
        return bonusNumber;
    }

    private void validateNumber(String price) throws IllegalArgumentException {
        try {
            Integer.parseInt(price);
        } catch (NumberFormatException e) {
            System.out.println("[ERROR] 숫자만 입력 가능합니다");
            throw new IllegalArgumentException();
        }
    }

    private void validateLottoFormat(String readSentence) {
        if (Pattern.matches("[^0-9,]+", readSentence)) {
            System.out.println("[ERROR] 올바르지 않은 형식입니다");
            throw new IllegalArgumentException();
        }
    }
}
```

해당 클래스를 새로 만들어서, 문자열 입력에 대한 예외처리를 view에서 해주도록 하고,
domain에는 list<Integer 만 인식할 수 있도록 코드를 리팩토링했습니다.

2023-07-05 12:06 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/WinningLotto.java
> +public final class WinningLotto extends Lotto {
WinningLotto는 로또 번호 6개 + bonus인데,
로또 번호 6개를 Lotto라는 상위 클래스로 만들어서 코드의 중복을 줄이기 위해 사용했습니다.

상속을 이용한 단점은 제가 생각하기에
1. 클래스간의 결합도가 강해진다.
2. 부모 자식 클래스 간의 캡슐화가 깨질 수 있다.
3. 코드 복잡도가 올라간다.

상속을 이용한 장점은
1. 객체의 재사용(코드의 재사용)
2. 어떤 클래스 간의 상속을 보고 관계를 명시적으로 유추할 수 있다?

2023-07-05 12:08 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/WinningLotto.java
> +public final class WinningLotto extends Lotto {
사실 인터페이스를 이용하면 더 좋을거같은데, 정확히 사용하는 법을 잘 모르겠어서
어설프게 쓸빠에 그냥 상속을 사용했습니다.

2023-07-05 12:27 UTC, howudong commented on src/main/java/lotto/domain/lottonumber/Lotto.java
> +    final List<Integer> getNumbers() {
해당 함수는 자식 클래스인 WinningLotto 클래스에서 오버라이딩을 방지하기 위해 final을 붙였습니다.
오버라이딩을 방지하는 이유는 getNumbers는 로또 번호를 얻는 것 그 이상 이하도 아니고 싶기 때문이었습니다.

2023-07-05 13:30 UTC, howudong commented on src/main/java/lotto/domain/LottoResult.java
> +    }
```
package lotto.domain;

import lotto.domain.lottonumber.Lotto;
import lotto.domain.lottonumber.WinningLotto;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

class LottoResultTest {

    @DisplayName("RANK FIRST 반환되어야 한다.")
    @Test
    void getLottoFIRSTRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(1, 2, 3, 4, 5, 6)),
                new Lotto(List.of(2, 1, 5, 6, 4, 3)),
                new Lotto(List.of(6, 5, 4, 3, 2, 1))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.FIRST);
        }
    }

    @DisplayName("RANK SECOND 반환되어야 한다.")
    @Test
    void getLottoSECONDRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(45, 2, 3, 4, 5, 6)),
                new Lotto(List.of(2, 1, 45, 6, 4, 3)),
                new Lotto(List.of(6, 5, 4, 3, 45, 1))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.SECOND);
        }
    }

    @DisplayName("RANK THIRD 반환되어야 한다.")
    @Test
    void getLottoTHIRDRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(30, 2, 3, 4, 5, 6)),
                new Lotto(List.of(2, 1, 42, 6, 4, 3)),
                new Lotto(List.of(6, 5, 4, 3, 44, 1))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.THIRD);
        }
    }

    @DisplayName("RANK FOURTH 반환되어야 한다.")
    @Test
    void getLottoFOURTHRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(30, 21, 3, 4, 5, 6)),
                new Lotto(List.of(2, 1, 42, 6, 41, 3)),
                new Lotto(List.of(6, 5, 4, 33, 44, 1))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.FOURTH);
        }
    }

    @DisplayName("RANK FIFTH 반환되어야 한다.")
    @Test
    void getLottoFIFTHRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(30, 21, 31, 4, 5, 6)),
                new Lotto(List.of(24, 1, 42, 6, 45, 3)),
                new Lotto(List.of(6, 5, 4, 33, 44, 45))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.FIFTH);
        }
    }

    @DisplayName("RANK FIFTH 반환되어야 한다.")
    @Test
    void getLottoUNRANKEDRanks() {
        WinningLotto winningLotto = new WinningLotto(List.of(1, 2, 3, 4, 5, 6), 45);
        List<Lotto> lotto = List.of(
                new Lotto(List.of(30, 21, 31, 4, 5, 20)),
                new Lotto(List.of(24, 10, 42, 7, 45, 8)),
                new Lotto(List.of(6, 15, 41, 33, 44, 45))
        );
        List<LottoRank> ranks = new LottoResult().getLottoRanks(lotto, winningLotto);
        for (LottoRank rank : ranks) {
            Assertions.assertThat(rank).isEqualTo(LottoRank.UNRANKED);
        }
    }
}
```

테스트 로직 설계하고 테스트 다 통과했습니다.

2023-07-05 13:38 UTC, closed without merging